[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["orkhan.mamedov <orkhan.mamedov@sravni.ru>"]

[tool.poetry.dependencies]
python = "^3.8.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
