version: '3.1'
services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  queue:
    image: rabbitmq:3

  backend:
    image: backend
    ports:
      - 10088:80
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: .
      dockerfile: backend.dockerfile

  worker:
    image: worker
    depends_on:
      - db
      - queue
    env_file:
      - .env
    build:
      context: .
      dockerfile: celeryworker.dockerfile