version: '3.1'
services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:6.0.3-alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  worker:
    image: rqworker
    depends_on:
      - db
      - redis
    env_file:
      - .env
    build:
      context: .
      dockerfile: rqworker.dockerfile

#  backend:
#    image: backend
#    ports:
#      - 10088:80
#    depends_on:
#      - db
#    env_file:
#      - .env
#    build:
#      context: .
#      dockerfile: backend.dockerfile